train_dataset: nuscenes
#dataroot: ${DATA_ROOT}/nuscenes
# #nuscenes-mini
dataroot: /workspace/dataset/nuscenes/mini
nuscenes_version: v1.0-mini
label_root: /workspace/dataset/nuscenes/map-labels-mini
#road_layout_root: /workspace/dataset/nuscenes/map-labels-mini-roadLayout
road_layout_root: /home/gs/workspace/datasets/nuscenes_processed/map-labels-mini-roadLayout-multicls

# #nuscenes-trainval
# dataroot: /workspace/dataset/nuscenes/trainval
# nuscenes_version: v1.0-trainval
# label_root: /workspace/dataset/nuscenes/map-labels-v1.2
# #road_layout_root: /workspace/dataset/nuscenes/map-labels-v1.2-roadLayout
# road_layout_root: /home/gs/workspace/datasets/nuscenes_processed/map-labels-v1.2-roadLayout-multicls

img_size: [800, 450]
num_class: 14
class_weights:
  -    1.7    # drivable_area
  -    5.9    # ped_crossing
  -    3.3    # walkway
  -    4.6    # carpark
  -    8.0    # car
  -   10.3    # truck
  -   10.6    # bus
  -    6.9    # trailer
  -   11.8    # construction_vehicle
  -   30.1    # pedestrian
  -   33.6    # motorcycle
  -   41.2    # bicycle
  -   44.3    # traffic_cone
  -   15.9    # barrier

# Prior probability of a positive prediction, used to initialise classifier
prior: 
  - 0.44679   # drivable_area
  - 0.02407   # ped_crossing
  - 0.14491   # walkway
  - 0.02994   # carpark
  - 0.02086   # car
  - 0.00477   # truck
  - 0.00156   # bus
  - 0.00189   # trailer
  - 0.00084   # construction_vehicle
  - 0.00119   # pedestrian
  - 0.00019   # motorcycle
  - 0.00012   # bicycle
  - 0.00031   # traffic_cone
  - 0.00176   # barrier

ved:
  bottleneck_dim: 18

vpn:
  output_size : [29, 50]